[site]
title = "刘城 - 个人主页"
description = "西班牙 ICMAB-CSIC 博士生。"
favicon = "/docs/assets/images/favicon.svg"
last_updated = "2025年11月20日"

[author]
name = "刘城"
title = "博士生"
institution = "西班牙 ICMAB-CSIC"
avatar = "/docs/assets/images/bio.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "liuchzzyy@163.com"
location = "西班牙巴塞罗那"
location_url = "https://www.google.com/maps/place/Institute+of+Materials+Science+of+Barcelona+(ICMAB-CSIC)/@35.226773,-17.4123491,5z/data=!4m10!1m2!2m1!1sicmab!3m6!1s0x12a495d5f8a1143b:0x20d754b9dfa8a7ca!8m2!3d41.5020566!4d2.1103129!15sCgVpY21hYloHIgVpY21hYpIBEnJlc2VhcmNoX2luc3RpdHV0ZZoBJENoZERTVWhOTUc5blMwVkpRMEZuU1VNdGIwMURUekYzUlJBQuABAPoBBAgAECQ!16s%2Fg%2F1tg09w5y?entry=ttu&g_ep=EgoyMDI1MTIwOS4wIKXMDSoASAFQAw%3D%3D"
location_details = [
  "Universitat Autònoma de Barcelona, Campus de la, Carrer dels Til·lers, s/n, 08193 Bellaterra, Barcelona, Spain"
]
google_scholar = "https://scholar.google.com/citations?user=E7pDru4AAAAJ&hl=en"
orcid = "https://orcid.org/0000-0001-8967-1174"
github = "https://github.com/liuchzzyy"
xiaohongshu = "https://www.xiaohongshu.com/user/profile/67154fd1000000001d02113d"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "关于我"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "学术成果"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "项目"
type = "page"
target = "projects"
href = "/projects"

[[navigation]]
title = "新闻"
type = "page"
target = "news"
href = "/news"

[[navigation]]
title = "技术"
type = "page"
target = "techniques"
href = "/techniques"

[[navigation]]
title = "简历"
type = "page"
target = "resume"
href = "/resume"
