type = "list"
title = "æ–°é—»åŠ¨æ€"
description = "æœ€æ–°åŠ¨æ€å’Œå…¬å‘Šã€‚"

[[items]]
date = "2025-11-01"
content = "æˆ‘ä»¬çš„å·¥ä½œå·²è¢«ä¸€å®¶è‘—åæœŸåˆŠæ¥æ”¶ ğŸ‰"
image = "example.png"

[[items]]
date = "2025-09-01"
content = "å¼€å§‹åœ¨ç¤ºä¾‹å¤§å­¦æ”»è¯»åšå£«å­¦ä½"
image = "example.png"
